import SwiftUI

struct PlaybackView: View {
    let story: StoryItem
    @ObservedObject var vm: StoryViewModel
    @State private var isPlaying = false

    var body: some View {
        ZStack {
            LinearGradient(
                colors: [Color(hex: "0A0818"), Color(hex: "1C1050"), Color(hex: "0A0818")],
                startPoint: .top, endPoint: .bottom
            )
            .ignoresSafeArea()

            VStack(spacing: 32) {
                Spacer()

                // Cover art
                ZStack {
                    RoundedRectangle(cornerRadius: 28, style: .continuous)
                        .fill(story.mood.cardGradient)
                        .frame(width: 220, height: 220)
                        .shadow(color: .black.opacity(0.5), radius: 30, x: 0, y: 15)

                    Image(systemName: story.mood.icon)
                        .font(.system(size: 70))
                        .foregroundColor(.white.opacity(0.85))
                }

                // Info
                VStack(spacing: 6) {
                    Text(story.title)
                        .font(.system(size: 22, weight: .semibold, design: .rounded))
                        .foregroundColor(.white)
                    Text("\(story.mood.rawValue) · \(story.language.rawValue)")
                        .font(.system(size: 14, design: .rounded))
                        .foregroundColor(.white.opacity(0.45))
                    HStack(spacing: 4) {
                        Image(systemName: "sparkles").font(.system(size: 10))
                        Text("Generated by AI")
                            .font(.system(size: 11, design: .rounded))
                    }
                    .foregroundColor(Color(hex: "A87FE0").opacity(0.8))
                }

                // Progress
                VStack(spacing: 8) {
                    ProgressBar()
                    HStack {
                        Text("0:00").font(.system(size: 11, design: .rounded)).foregroundColor(.white.opacity(0.4))
                        Spacer()
                        Text("\(story.durationMinutes):00").font(.system(size: 11, design: .rounded)).foregroundColor(.white.opacity(0.4))
                    }
                }
                .padding(.horizontal, 32)

                // Controls
                HStack(spacing: 48) {
                    Button { } label: {
                        Image(systemName: "gobackward.15")
                            .font(.system(size: 26))
                            .foregroundColor(.white.opacity(0.7))
                    }.buttonStyle(.plain)

                    Button {
                        withAnimation(.spring(response: 0.3)) { isPlaying.toggle() }
                    } label: {
                        ZStack {
                            Circle().fill(Color(hex: "7B5EA7")).frame(width: 64, height: 64)
                            Image(systemName: isPlaying ? "pause.fill" : "play.fill")
                                .font(.system(size: 24)).foregroundColor(.white)
                        }
                    }.buttonStyle(.plain)

                    Button { } label: {
                        Image(systemName: "goforward.15")
                            .font(.system(size: 26))
                            .foregroundColor(.white.opacity(0.7))
                    }.buttonStyle(.plain)
                }

                // Sleep timer
                Button { vm.showSleepTimerSheet = true } label: {
                    HStack(spacing: 8) {
                        Image(systemName: "moon.zzz.fill").font(.system(size: 14))
                        Text("Sleep timer")
                            .font(.system(size: 14, weight: .medium, design: .rounded))
                    }
                    .foregroundColor(.white.opacity(0.55))
                    .padding(.horizontal, 20).padding(.vertical, 11)
                    .background(Color.white.opacity(0.07))
                    .clipShape(Capsule())
                }
                .buttonStyle(.plain)

                Spacer()
            }
        }
        .navigationTitle("")
        .navigationBarTitleDisplayMode(.inline)
        .toolbarBackground(.hidden, for: .navigationBar)
        .toolbarColorScheme(.dark, for: .navigationBar)
        .sheet(isPresented: $vm.showSleepTimerSheet) {
            SleepTimerSheet(vm: vm)
                .presentationDetents([.medium])
                .presentationDragIndicator(.visible)
                .presentationBackground(Color(hex: "16102E"))
        }
    }
}

#Preview {
    NavigationStack {
        PlaybackView(story: StoryItem.samples[0], vm: StoryViewModel())
    }
    .preferredColorScheme(.dark)
}
