import SwiftUI

struct StoryPlayingView: View {
    @ObservedObject var vm: StoryViewModel
    @State private var pulse = false
    @State private var outerPulse = false
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        ZStack {
            // Background
            LinearGradient(
                colors: [Color(hex: "0A0818"), Color(hex: "1C1050"), Color(hex: "0A0818")],
                startPoint: .top, endPoint: .bottom
            )
            .ignoresSafeArea()

            // Ambient glow behind orb
            Circle()
                .fill(Color(hex: "A87FE0").opacity(0.18))
                .frame(width: 280, height: 280)
                .scaleEffect(outerPulse ? 1.25 : 0.95)
                .blur(radius: 40)
                .animation(.easeInOut(duration: 3).repeatForever(autoreverses: true), value: outerPulse)

            VStack(spacing: 0) {
                Spacer()

                // MARK: Glowing Orb (the "sun" from the sketch)
                ZStack {
                    // Outer ring 2
                    Circle()
                        .stroke(Color(hex: "A87FE0").opacity(0.12), lineWidth: 1)
                        .frame(width: 220, height: 220)
                        .scaleEffect(pulse ? 1.12 : 0.92)

                    // Outer ring 1
                    Circle()
                        .stroke(Color(hex: "A87FE0").opacity(0.22), lineWidth: 1.5)
                        .frame(width: 185, height: 185)
                        .scaleEffect(pulse ? 1.08 : 0.95)

                    // Main orb
                    Circle()
                        .fill(
                            RadialGradient(
                                colors: [
                                    Color(hex: "D4B0FF"),
                                    Color(hex: "A87FE0"),
                                    Color(hex: "6B3FA0"),
                                ],
                                center: .center,
                                startRadius: 0,
                                endRadius: 75
                            )
                        )
                        .frame(width: 148, height: 148)
                        .shadow(color: Color(hex: "A87FE0").opacity(0.6), radius: 30, x: 0, y: 0)
                        .scaleEffect(pulse ? 1.04 : 0.97)

                    // Play/pause icon
                    Button {
                        withAnimation(.spring(response: 0.3)) {
                            vm.isPlaying.toggle()
                        }
                    } label: {
                        Image(systemName: vm.isPlaying ? "pause.fill" : "play.fill")
                            .font(.system(size: 30))
                            .foregroundColor(.white.opacity(0.9))
                    }
                    .buttonStyle(.plain)
                }
                .onAppear {
                    withAnimation(.easeInOut(duration: 2.8).repeatForever(autoreverses: true)) {
                        pulse = true
                    }
                    withAnimation(.easeInOut(duration: 4).repeatForever(autoreverses: true)) {
                        outerPulse = true
                    }
                }

                Spacer().frame(height: 40)

                // Story info
                VStack(spacing: 8) {
                    Text(vm.generatedStory?.title ?? "Your Story")
                        .font(.system(size: 22, weight: .semibold, design: .rounded))
                        .foregroundColor(.white)
                        .multilineTextAlignment(.center)

                    HStack(spacing: 6) {
                        Text(vm.selectedMood?.rawValue ?? "")
                        Text("·")
                        Text(vm.selectedLanguage?.rawValue ?? "")
                        Text("·")
                        Text(vm.selectedLength?.label ?? "")
                    }
                    .font(.system(size: 13, design: .rounded))
                    .foregroundColor(.white.opacity(0.45))

                    // AI disclosure (App Store guideline 1.2)
                    HStack(spacing: 4) {
                        Image(systemName: "sparkles")
                            .font(.system(size: 10))
                        Text("Generated by AI")
                            .font(.system(size: 11, design: .rounded))
                    }
                    .foregroundColor(Color(hex: "A87FE0").opacity(0.8))
                    .padding(.top, 2)
                }
                .padding(.horizontal, 32)

                Spacer().frame(height: 40)

                // Progress bar
                VStack(spacing: 8) {
                    ProgressBar()
                    HStack {
                        Text("0:00")
                            .font(.system(size: 11, design: .rounded))
                            .foregroundColor(.white.opacity(0.4))
                        Spacer()
                        Text("\(vm.selectedLength?.rawValue ?? 20):00")
                            .font(.system(size: 11, design: .rounded))
                            .foregroundColor(.white.opacity(0.4))
                    }
                }
                .padding(.horizontal, 32)

                Spacer().frame(height: 32)

                // Transport controls
                HStack(spacing: 48) {
                    Button {
                        // rewind 15s
                    } label: {
                        Image(systemName: "gobackward.15")
                            .font(.system(size: 26))
                            .foregroundColor(.white.opacity(0.7))
                    }
                    .buttonStyle(.plain)

                    Button {
                        withAnimation(.spring(response: 0.3)) {
                            vm.isPlaying.toggle()
                        }
                    } label: {
                        ZStack {
                            Circle()
                                .fill(Color(hex: "7B5EA7"))
                                .frame(width: 64, height: 64)
                            Image(systemName: vm.isPlaying ? "pause.fill" : "play.fill")
                                .font(.system(size: 24))
                                .foregroundColor(.white)
                        }
                    }
                    .buttonStyle(.plain)

                    Button {
                        // forward 15s
                    } label: {
                        Image(systemName: "goforward.15")
                            .font(.system(size: 26))
                            .foregroundColor(.white.opacity(0.7))
                    }
                    .buttonStyle(.plain)
                }

                Spacer().frame(height: 36)

                // Sleep timer button
                Button {
                    vm.showSleepTimerSheet = true
                } label: {
                    HStack(spacing: 8) {
                        Image(systemName: "moon.zzz.fill")
                            .font(.system(size: 14))
                        Text(vm.sleepTimer == .off ? "Sleep timer" : "Timer: \(vm.sleepTimer.label)")
                            .font(.system(size: 14, weight: .medium, design: .rounded))
                    }
                    .foregroundColor(vm.sleepTimer == .off ? .white.opacity(0.55) : Color(hex: "A87FE0"))
                    .padding(.horizontal, 20)
                    .padding(.vertical, 11)
                    .background(Color.white.opacity(0.07))
                    .clipShape(Capsule())
                }
                .buttonStyle(.plain)

                Spacer(minLength: 40)
            }
        }
        .navigationTitle("")
        .navigationBarTitleDisplayMode(.inline)
        .toolbarBackground(.hidden, for: .navigationBar)
        .toolbarColorScheme(.dark, for: .navigationBar)
        .sheet(isPresented: $vm.showSleepTimerSheet) {
            SleepTimerSheet(vm: vm)
                .presentationDetents([.medium])
                .presentationDragIndicator(.visible)
                .presentationBackground(Color(hex: "16102E"))
        }
    }
}

// MARK: - Animated progress bar
struct ProgressBar: View {
    @State private var progress: Double = 0.0
    var body: some View {
        GeometryReader { geo in
            ZStack(alignment: .leading) {
                RoundedRectangle(cornerRadius: 3)
                    .fill(Color.white.opacity(0.12))
                    .frame(height: 4)
                RoundedRectangle(cornerRadius: 3)
                    .fill(Color(hex: "A87FE0"))
                    .frame(width: geo.size.width * progress, height: 4)
                    .animation(.linear(duration: 0.3), value: progress)
            }
        }
        .frame(height: 4)
        .onAppear {
            // Simulate playback progress
            Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { t in
                if progress < 1.0 { progress += 0.001 }
            }
        }
    }
}

#Preview {
    let vm = StoryViewModel()
    vm.selectedLanguage = .english
    vm.selectedMood = .calm
    vm.selectedLength = .twenty
    vm.isPlaying = true
    vm.generatedStory = StoryItem.samples[0]
    return NavigationStack {
        StoryPlayingView(vm: vm)
    }
    .preferredColorScheme(.dark)
}
